outputs_path: out
dataset_path: data
task: acronym_identification
gpus: 1
num_workers: 8
batch_size: 32
lr: 0.0001
eps: 1.0e-8
max_epochs: 10
freeze_first_n: 165
opt_step_size: 4
gamma: 0.1
weight_decay: 1.0e-4