outputs_path: /home/maria/Documents/TheGreatKnowledgeHeist/thegreatknowledgeheist
dataset_path: /home/maria/Documents/TheGreatKnowledgeHeist/thegreatknowledgeheist/data
task: swag
gpus: 1
num_workers: 8
batch_size: 8
lr: 0.001
eps: 1.0e-8
max_epochs: 50
