experiment_name: AMAZON-2-layers-no_kd
project_name: Final
output_path: out
model_name: "bert_solo"
save_checkpoint: False
task_name: "amazon_polarity"
data_config:
    path_to_dataset: data/amazon_polarity
    batch_size: 16
    num_workers: 8
model_config:
  pretrained: False
  bert_config:
    num_hidden_layers: 2
gpus: 1
adamw_start_lr: 1.0e-4
adamw_eps: 1.0e-8
adamw_weight_decay: 1.0e-5
scheduler_step_size: 5
scheduler_step_gamma: 0.1
number_of_epochs: 10

